audio:
  fps: 30
  max_samples: 44100
  n_mfcc: 20
  sample_interval: 0.03333333333333333
  sample_rate: 44100
  use_clean: true
  window_len: 0.025
emotions:
- angry
- contempt
- disgusted
- fear
- happy
- neutral
- sad
- surprised
files:
  data_root: processed_data
  face: processed_data/face.obj
  raw_data_root: MEAD
  subject_paths: processed_data/sbj_data_paths.pkl
  test:
    csv: processed_data/test_subjects.csv
    mini: processed_data/test_mini.csv
    root: processed_data/test
    subjects:
    - M003
    - M019
    - W009
    - W019
  train:
    csv: processed_data/train_subjects.csv
    mini: processed_data/train_mini.csv
    root: processed_data/train
    subjects:
    - M005
    - M007
    - M011
    - M012
    - M022
    - M023
    - M024
    - M025
    - M026
    - W014
    - W016
  val:
    csv: processed_data/val_subjects.csv
    mini: processed_data/val_mini.csv
    root: processed_data/val
    subjects:
    - M009
    - M013
    - W011
    - W015
model:
  fc:
    drop: 0.5
    hidden_1: 256
    hidden_2: 128
    hidden_3: 256
    hidden_4: 512
    in_feat: 576
  lstm:
    hidden_dim: 128
    num_layers: 1
  use_condition: true
  velocity_weight: 10.0
  vertex_num: 468
training:
  batch_size: 1
  consecutive_seqs: 2
  decay_rate: 0.95
  epochs: 300
  learning_rate: 0.00001
