audio:
  fps: 30
  max_samples: 16000
  n_mfcc: 20
  sample_interval: 0.03333333333333333
  sample_rate: 16000
  use_clean: true
  window_len: 0.025
files:
  data_root: processed_data
  face: processed_data/face.obj
  raw_data_root: MEAD
  subject_paths: processed_data/sbj_data_paths.pkl
  test:
    csv: processed_data/test_dataset.csv
    mini: processed_data/test_mini.csv
    root: processed_data/test
  train:
    csv: processed_data/train_dataset.csv
    mini: processed_data/train_mini.csv
    root: processed_data/train
  val:
    csv: processed_data/val_dataset.csv
    mini: processed_data/val_mini.csv
    root: processed_data/val
model:
  fc:
    drop: 0.7
    hidden_1: 256
    hidden_2: 128
    hidden_3: 256
    hidden_4: 512
    in_feat: 576
  lstm:
    hidden_dim: 16
    num_layers: 1
  velocity_weight: 10.0
  vertex_num: 468
training:
  batch_size: 64
  consecutive_seqs: 1
  decay_rate: 1.0
  epochs: 5
  learning_rate: 0.0001
