audio:
  fps: 30
  max_samples: 44100
  n_mfcc: 20
  sample_interval: 0.03333333333333333
  sample_rate: 44100
  window_len: 0.025
emotions:
- angry
- contempt
- disgusted
- fear
- happy
- neutral
- sad
- surprised
files:
  data_root: processed_data
  face: processed_data/face.obj
  raw_data_root: MEAD
  subject_paths: processed_data/sbj_data_paths.pkl
  train:
    csv: processed_data/train_dataset.csv
    mini: processed_data/train_mini.csv
    root: processed_data/train
    subjects:
    - M003
    - M009
    - M019
    - W009
    - W011
    - W019
  val:
    csv: processed_data/val_dataset.csv
    mini: processed_data/val_mini.csv
    root: processed_data/val
    subjects:
    - M013
    - W015
model:
  hidden_dim: 128
  num_layers: 1
  velocity_weight: 10.0
  vertex_num: 468
training:
  batch_size: 1
  decay_rate: 1.0
  epochs: 300
  learning_rate: 1.0e-06
